In [1]:
import pandas as pd
import requests

In [3]:
 response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=0574eaab6dd93d263849a8090fa2d73a&language=en-US&page=1')

In [15]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [16]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,182.311,8.700,27572
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,196.159,8.700,20919
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,107.942,8.600,12620
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,137.543,8.567,16063
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,74.962,8.500,8812

In [13]:
#Creating empty dataframe
df = pd.DataFrame()

In [14]:
df

Empty DataFrame
Columns: []
Index: []

In [19]:
for i in range(1,497):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=0574eaab6dd93d263849a8090fa2d73a&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [20]:
df.shape

(9915, 7)

In [21]:
df.to_csv('TopRated_movies.csv')